### ISSUE TITLE
maby me doing something wrong ?

### ISSUE THREAD

**Issue by bb1ox1bb** [RedToor/Katana#3]
root@xxx:/home/xxx# ktf.console
WARNING: No route found for IPv6 destination :: (no default route?)
Traceback (most recent call last):
  File "ktf.console.py", line 7, in <module>
    from scripts import *
  File "/usr/share/katana/scripts/__init__.py", line 14, in <module>
    import TLogin
  File "/usr/share/katana/scripts/TLogin.py", line 20, in <module>
    import pxssh                 #
ImportError: No module named pxssh

like i realised missing pxssh model on kali linux?

**Comment by RedToor** [comment]
Hi bb1ox1bb maybe pxssh is no install in you distro you can try change the line in TLogin.py (import pxssh) by (from pexpect import pxssh) 

Regards.

**Comment by bb1ox1bb** [comment]
thanx mate for quick response mery cristmas :)

2015-12-23 16:54 GMT+00:00 RedToor <notifications@github.com>:

**Comment by bb1ox1bb** [comment]
im on kali linux :) strange pentest distro like ini :)

2015-12-23 16:57 GMT+00:00 Boom Box <bb1ox1bb@gmail.com>:

**Comment by RedToor** [comment]
2.0?

**Comment by bb1ox1bb** [comment]
yap correct

2015-12-23 16:58 GMT+00:00 RedToor <notifications@github.com>:

**Comment by RedToor** [comment]
try update the library 

sudo pip install pexpect --upgrade

**Comment by bb1ox1bb** [comment]
[sudo] password for xxx:
Requirement already up-to-date: pexpect in /usr/lib/python2.7/dist-packages

2015-12-23 17:00 GMT+00:00 RedToor <notifications@github.com>:

**Comment by RedToor** [comment]
Uncomment for now all modules that use this library.
TLogin.py
BruteForceSSH.py
I'll search a solution soon.

**Comment by bb1ox1bb** [comment]
ok no wories

2015-12-23 19:28 GMT+00:00 RedToor <notifications@github.com>:

**Comment by RedToor** [comment]
Error FIxed in Last Update
